### ISSUE TITLE
Feature: Add build status when pull is queued

### ISSUE THREAD

**Issue by andyg0808** [danielbeardsley/cimpler#106]
# Problem
It appears that currently we only add the bubble to a PR when a build starts running. This risks a pull appearing to be ready before all the configured cimplers run on it.

# Do This
Make the git-build-status plugin listen for the `buildAdded` event:

https://github.com/danielbeardsley/cimpler/blob/56e2a0bebee2900a057d78adb7ef8d51e6dcdf95/plugins/github-commit-status.js#L11-L15

I think this carries the risk that builds which are filtered out by a Cimpler's `buildFilter` won't ever get their "complete" bubble, but that's also reflective of how Cimpler sees them: they stay in the queue forever.

**Comment by mlahargou** [comment]
What happens if we restart cimpler when there are builds queued?  Something to think about.

**Comment by danielbeardsley** [comment]
> What happens if we restart cimpler when there are builds queued? Something to think about.

Then they will keep their "queued" status until the builds are queued, then started.
