### ISSUE TITLE
GitHub: Stop using deprecated API authentication through query parameters

### ISSUE THREAD

**Issue by mlahargou** [danielbeardsley/cimpler#113]
Cimpler was down for 12 hours today from a brownout caused by the deprecation of API authentication through query params.

 

https://developer.github.com/changes/2020-02-10-deprecating-auth-through-query-param/

Brownouts:
```
May 5, 2021: For 12 hours starting at 14:00 UTC
June 9, 2021: For 24 hours starting at 14:00 UTC
August 11, 2021: For 48 hours starting at 14:00 UTC
```

https://github.com/danielbeardsley/cimpler/blob/9a5cc86c0d1e594537c81322c194c44f43688e84/plugins/github-commit-status.js#L45-L53

CC @danielbeardsley

**Comment by djmetzle** [comment]
This may involve upgrading to octokit?
https://www.npmjs.com/package/github

**Comment by mlahargou** [comment]
This is done.
